# Don't print a new line at the start of the prompt
add_newline = false

# single line prompt
[line_break]
disabled = true

# Show the status error number
[status]
disabled = false

[character]
success_symbol = "%"
error_symbol = "%"

# if python is enabled (and maybe its just pyenv) the shell speed is very slow
[python]
symbol = ""
# disabled = true

[git_branch]
symbol = ""
